language: node_js
sudo: false
dist: trusty
services:
  - rabbitmq
  - redis-server
cache:
  directories:
  - node_modules
node_js:
    - "9"
    - "8"
    - "6"
script:
  - npm test && npm run test:amqp
after_success:
  - npm run coverall
